In [1]:
import pandas as pd
import os
import re
from lamma_ask import run_llama

df= pd.read_csv('LifeQA/for_eval/new/OIC_llama_wo_st_updated.csv')
df['subtitle']= df['subtitle'].fillna('No subtitle')

df = df.drop_duplicates()
df.reindex()
df = df.dropna()
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

,q_id,question,answer_type,Answers,video_id,start,end,subtitle,OIC_context,OIC_question,ans_idx,OIC_answer_llama,Match_llama
0,1011,How many people are in the car?,V,"['11', '4', '2', '7']",TGUYv10XdTI,19.328000,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,How many people are in the car?Guess the most ...,2,2,Correct
1,1012,What color is the man's hat?,V,"['silver', 'golden', 'blue', 'red']",TGUYv10XdTI,19.328000,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,What color is the man's hat?Guess the most lik...,2,1,Wrong
2,1013,Where are they?,B,"['restroom', 'train', 'bedroom', 'car']",TGUYv10XdTI,19.328000,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,3,2,Wrong
3,1014,Where are they going?,L,"['class', 'restroom', 'party', 'mall']",TGUYv10XdTI,19.328000,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,Where are they going?Guess the most likely ans...,3,2,Wrong
4,1015,Where does she want to go to first?,L,"['Aldo', 'home', 'Zara', 'Forever XXI']",TGUYv10XdTI,19.328000,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,Where does she want to go to first?Guess the m...,3,2,Wrong
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911,2282,How many full glasses of water are?,B,"['1', '2', '3', '13']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with glass_e8e6 on table_8713\...,How many full glasses of water are?Guess the m...,1,2,Wrong
1912,2283,What is the boy's name?,L,"['Joel', 'James', 'Mario', 'Jean']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with glass_e8e6 on table_8713\...,What is the boy's name?Guess the most likely a...,1,2,Wrong
1913,2284,How many cups are there?,V,"['3', '1', '4', '2']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with glass_e8e6 on table_8713\...,How many cups are there?Guess the most likely ...,0,1,Wrong
1914,2285,Does James think that there is the same amount...,L,"['yes', '', 'no', '']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with glass_e8e6 on table_8713\...,Does James think that there is the same amount...,0,1,Wrong
1915,2286,Does James think that there is the same amount...,L,"['no', '', '', 'yes']",SrBp1Ojt5Z0,136.533333,225.664000,[woman] ok so James do you think these both gl...,The scene opens with glass_e8e6 on table_8713\...,Does James think that there is the same amount...,0,1,Wrong

In [2]:
df['OIC_context_without_CUID'] =  df['OIC_context'].apply(lambda x: re.sub('_[a-zA-Z0-9]*', '', x))
df['OIC_context_without_CUID'][0]

'The scene opens with woman wearing shirt\nwoman in car\nwoman wearing hat\nAfter 1 seconds:\near of woman\nAfter 2 seconds:\nshirt on woman\nAfter     7 seconds:\nhat on head\nAfter  9 seconds:\nshirt on woman\nwoman wearing shirt\nAfter  11 seconds:\nshirt on woman\nhat on head\nhat on woman\nAfter 12 seconds:\near of man\nman wearing shirt\nman wearing hat\nAfter  14 seconds:\nman in car\nAfter 15 seconds:\nshirt on woman\near of woman\nwoman wearing hat\nAfter 16 seconds:\nwoman wearing hat\nboy wearing shirt\nglass on face\nAfter 17 seconds:\near of boy\nboy wearing hat\nAfter  19 seconds:\nshirt on woman\near of woman\nwoman wearing shirt\nwoman wearing hat\nboy wearing hat\nAfter 20 seconds:\nwoman wearing glass\nAfter 21 seconds:\nwoman wearing hat\nAfter 22 seconds:\nwoman in car\nwoman wearing glass\nwoman in car\nAfter 23 seconds:\nwoman holding phone\nwoman wearing tie\nhat on woman\nAfter  25 seconds:\nphone in hand\nAfter 26 seconds:\nhat on woman\nboy wearing shirt\nboy wearing hat\nAfter 27 seconds:\nshirt on woman\near of woman\nAfter 28 seconds:\nshirt on woman\nwoman wearing hat\nAfter  30 seconds:\nwoman in car\nwoman wearing hat\nwoman wearing hat\nAfter   33 seconds:\nwoman in car\nAfter  35 seconds:\nwoman wearing hat\nhat on woman\nAfter 36 seconds:\nwoman wearing hat\nAfter 37 seconds:\nhair on woman\nwoman in car\nAfter 38 seconds:\nshirt on woman\nAfter 39 seconds:\nhair on woman\nwindow on car\nAfter 40 seconds:\nnose on face\nAfter 41 seconds:\nwindow of car\nAfter 42 seconds:\nman wearing shirt\nAfter 43 seconds:\nhair on head\nwindow on car\nhandle on door\nseat in car\nAfter 44 seconds:\nhair on child\near on head\nwindow of car\nwindow on door\nAfter 45 seconds:\nwoman wearing shirt\nwoman in car\nwindow on car\nseat in car\nAfter 46 seconds:\nwoman wearing glove\nAfter  48 seconds:\nman wearing shirt\nnose on face\nwindow of car\nAfter 49 seconds:\nhair on woman\nwindow on car\nAfter 50 seconds:\nshirt on woman\nAfter 51 seconds:\nhair on woman\nAfter 52 seconds:\near of woman\nwindow of car\nAfter 53 seconds:\nman wearing tie\nwindow on car\nwindow on door\nhandle on door\nhandle on car\nAfter 54 seconds:\nwoman wearing tie\nman wearing shirt\ntie on woman\nnose on face\nwindow of car\nAfter 55 seconds:\nwindow on car\nAfter 56 seconds:\nwindow of car\nAfter 57 seconds:\nshirt on woman\near of woman\nwindow on car\nAfter   60 seconds:\nwindow of car\nAfter 61 seconds:\nhandle on door\nAfter 62 seconds:\nshirt on woman\nwindow on car\nwindow of car\nAfter 63 seconds:\nwoman wearing tie\nshirt on shirt\nmouth on woman\nwindow behind woman\nAfter 64 seconds:\nwoman wearing shirt\nmouth on woman\nhand of woman\ntie on woman\nnose on face\nwindow of car\nneck of woman\nAfter 65 seconds:\nwoman in car\nhair on woman\nAfter 66 seconds:\nwoman wearing tie\nnose on face\nAfter 67 seconds:\nchild in car\nAfter  69 seconds:\nshirt on woman\nman wearing shirt\nman in car\nwindow on car\nAfter 70 seconds:\nwoman wearing hat\nshirt on woman\near of woman\nhat on woman\nwoman wearing shirt\nwoman wearing hat\nAfter  72 seconds:\nwoman wearing glass\nAfter 73 seconds:\nhat on woman\nman wearing shirt\nAfter  75 seconds:\nwoman wearing hat\near of man\nhat on head\nman wearing shirt\nman wearing hat\nAfter 76 seconds:\nwoman wearing hat\nAfter 77 seconds:\nwoman wearing hat\nnose on face\near of woman\nAfter 78 seconds:\nshirt on woman\near of man\nAfter 79 seconds:\nface of woman\nman wearing hat\nboy in car\nhead on woman\nAfter 80 seconds:\nwoman wearing hat\nshirt on woman\nhat on woman\nwoman wearing hat\near of woman\near of woman\nhelmet on woman\nAfter 81 seconds:\nshirt on woman\nwoman wearing helmet\nman wearing shirt\nman wearing hat\near of woman\nhelmet on head\nAfter 82 seconds:\nwoman wearing hat\nAfter 83 seconds:\nshirt on woman\nhat on woman\nhand of woman\nAfter 84 seconds:\nwoman wearing glass\nboy wearing shirt\nAfter 85 seconds:\nhat on woman\nman wearing shirt\nman wearing hat\nboy in car\nAfter 86 seconds:\nshirt on woman\nhat on man\near of man\nAfter 87 seconds:\nwoman wearing shirt\nwoman wearing hat\nwoman wearing glass\nshirt on woman\nwoman wearing shirt\near of woman\nlogo on shirt\nAfter 88 seconds:\near of woman\near of woman\near of woman\nAfter  90 seconds:\nwoman wearing shirt\nshirt on woman\nAfter 91 seconds:\nwoman wearing glass\nwoman in car\nman wearing shirt\nAfter 92 seconds:\near of woman\nAfter 93 seconds:\nwoman wearing hat\nhat on woman\nwoman in car\nAfter 94 seconds:\nwoman in car\near of woman\nAfter 95 seconds:\nman wearing shirt\nhand of woman\near of woman\nAfter  97 seconds:\nwoman wearing hat\nwoman wearing glass\nwoman wearing hat\nAfter  99 seconds:\nwoman wearing hat\nhat on woman\nwoman wearing hat\nAfter 100 seconds:\near of woman\nAfter 101 seconds:\nwoman wearing hat\nshirt on woman\nwoman wearing hat\nwoman holding phone\nAfter 102 seconds:\nhat on woman\near of woman\nAfter 103 seconds:\near of woman\near of woman\near of woman\nAfter 104 seconds:\nshirt on woman\nwoman holding glass\nman wearing shirt\nAfter  106 seconds:\near of woman\nAfter 107 seconds:\nwoman wearing hat\near of woman\nshirt on woman\nAfter   110 seconds:\nshirt on woman\near of woman\nAfter  112 seconds:\nwoman in car\nAfter  114 seconds:\nshirt on woman\narm of woman\nman wearing shirt\nman wearing glass\nAfter  116 seconds:\nwoman holding phone\nhand of woman\near of woman\nAfter 117 seconds:\nwoman wearing hat\nhat on woman\nAfter 118 seconds:\nhat on head\near of woman\nshirt on woman\nAfter 119 seconds:\nshirt on woman\nwoman wearing hat\nAfter 120 seconds:\nman wearing shirt\nman wearing hat\nshirt on woman\nAfter 121 seconds:\nwoman wearing hat\nshirt on woman\nhelmet on woman\nAfter 122 seconds:\nwoman in car\nman in car\nAfter 123 seconds:\nshirt on woman\nAfter 124 seconds:\nwoman wearing hat\nman wearing shirt\nshirt on woman\nAfter 125 seconds:\nhelmet on woman\nAfter   128 seconds:\nwoman wearing hat\nman wearing hat\near of woman\nAfter 129 seconds:\nwoman wearing hat\nAfter 130 seconds:\nhat on head\nhat on woman\nwoman wearing shirt\nAfter    134 seconds:\nshirt on woman\nwoman wearing hat\nhelmet on woman\nAfter 135 seconds:\nwoman in car\nhelmet on head\nAfter 136 seconds:\nwoman wearing helmet\nAfter 137 seconds:\nwoman wearing hat\nman in car\nshirt on woman\nAfter 138 seconds:\nshirt on woman\nhat on head\nAfter 139 seconds:\nhat on woman\nAfter 140 seconds:\nwoman wearing hat\nhelmet on head\nAfter  142 seconds:\nwoman wearing hat\nwoman on phone\nAfter 143 seconds:\nwoman wearing hat\nhat on head\nhat on woman\nAfter  145 seconds:\nhat on woman\nwoman wearing hat\nAfter  147 seconds:\nman wearing shirt\nman wearing hat\nshirt on woman\nAfter 148 seconds:\nman in car\nAfter 149 seconds:\nwoman wearing shirt\nshirt on woman\nhat on head\nwoman wearing hat\nhelmet on woman\nhelmet on head\near of woman\nAfter 150 seconds:\nwoman wearing hat\nhat on woman\nwoman in car\nboy wearing shirt\nAfter 151 seconds:\nman wearing shirt\nboy in car\nhelmet on head\nAfter 152 seconds:\nshirt on woman\nAfter 153 seconds:\nman wearing shirt\nman in car\nAfter 154 seconds:\nwoman in car\nAfter 155 seconds:\nman wearing helmet\nhelmet on head\near of woman\nshirt on woman\nAfter 156 seconds:\nwoman wearing hat\nAfter  158 seconds:\nwoman in car\nAfter  160 seconds:\nhat on head\nAfter 161 seconds:\nshirt on woman\nwoman in car\near of woman\nshirt on woman\nAfter 162 seconds:\nwoman in car\near of woman\nhelmet on woman\nAfter 163 seconds:\nshirt on woman\nman wearing shirt\nman wearing hat\nphone in hand\near of woman\nAfter 164 seconds:\nshirt on woman\nAfter 165 seconds:\nhat on head\nAfter 166 seconds:\nshirt on woman\nwoman wearing hat\nman wearing shirt\nhand of woman\near of woman\nAfter 167 seconds:\near of woman\nshirt on woman\nAfter 168 seconds:\nman wearing shirt\nman wearing hat\nhand of woman\nhelmet on woman\near of woman\nAfter  170 seconds:\nwoman in car\near of woman\n'

In [3]:
class Substitutable(str):
  def __new__(cls, *args, **kwargs):
    newobj = str.__new__(cls, *args, **kwargs)
    newobj.sub = lambda fro,to: Substitutable(re.sub(fro, to, newobj))
    return newobj

In [4]:
df['OIC_context_without_CUID_temp'] = df['OIC_context_without_CUID'].apply(lambda x: Substitutable(x).sub('\n', ', ').sub('The scene opens with', '').sub('After', '').sub(' [0-9]* seconds:', ''))

df['OIC_context_without_CUID_temp'][0]

' woman wearing shirt, woman in car, woman wearing hat, , ear of woman, , shirt on woman,     , hat on head,  , shirt on woman, woman wearing shirt,  , shirt on woman, hat on head, hat on woman, , ear of man, man wearing shirt, man wearing hat,  , man in car, , shirt on woman, ear of woman, woman wearing hat, , woman wearing hat, boy wearing shirt, glass on face, , ear of boy, boy wearing hat,  , shirt on woman, ear of woman, woman wearing shirt, woman wearing hat, boy wearing hat, , woman wearing glass, , woman wearing hat, , woman in car, woman wearing glass, woman in car, , woman holding phone, woman wearing tie, hat on woman,  , phone in hand, , hat on woman, boy wearing shirt, boy wearing hat, , shirt on woman, ear of woman, , shirt on woman, woman wearing hat,  , woman in car, woman wearing hat, woman wearing hat,   , woman in car,  , woman wearing hat, hat on woman, , woman wearing hat, , hair on woman, woman in car, , shirt on woman, , hair on woman, window on car, , nose on face, , window of car, , man wearing shirt, , hair on head, window on car, handle on door, seat in car, , hair on child, ear on head, window of car, window on door, , woman wearing shirt, woman in car, window on car, seat in car, , woman wearing glove,  , man wearing shirt, nose on face, window of car, , hair on woman, window on car, , shirt on woman, , hair on woman, , ear of woman, window of car, , man wearing tie, window on car, window on door, handle on door, handle on car, , woman wearing tie, man wearing shirt, tie on woman, nose on face, window of car, , window on car, , window of car, , shirt on woman, ear of woman, window on car,   , window of car, , handle on door, , shirt on woman, window on car, window of car, , woman wearing tie, shirt on shirt, mouth on woman, window behind woman, , woman wearing shirt, mouth on woman, hand of woman, tie on woman, nose on face, window of car, neck of woman, , woman in car, hair on woman, , woman wearing tie, nose on face, , child in car,  , shirt on woman, man wearing shirt, man in car, window on car, , woman wearing hat, shirt on woman, ear of woman, hat on woman, woman wearing shirt, woman wearing hat,  , woman wearing glass, , hat on woman, man wearing shirt,  , woman wearing hat, ear of man, hat on head, man wearing shirt, man wearing hat, , woman wearing hat, , woman wearing hat, nose on face, ear of woman, , shirt on woman, ear of man, , face of woman, man wearing hat, boy in car, head on woman, , woman wearing hat, shirt on woman, hat on woman, woman wearing hat, ear of woman, ear of woman, helmet on woman, , shirt on woman, woman wearing helmet, man wearing shirt, man wearing hat, ear of woman, helmet on head, , woman wearing hat, , shirt on woman, hat on woman, hand of woman, , woman wearing glass, boy wearing shirt, , hat on woman, man wearing shirt, man wearing hat, boy in car, , shirt on woman, hat on man, ear of man, , woman wearing shirt, woman wearing hat, woman wearing glass, shirt on woman, woman wearing shirt, ear of woman, logo on shirt, , ear of woman, ear of woman, ear of woman,  , woman wearing shirt, shirt on woman, , woman wearing glass, woman in car, man wearing shirt, , ear of woman, , woman wearing hat, hat on woman, woman in car, , woman in car, ear of woman, , man wearing shirt, hand of woman, ear of woman,  , woman wearing hat, woman wearing glass, woman wearing hat,  , woman wearing hat, hat on woman, woman wearing hat, , ear of woman, , woman wearing hat, shirt on woman, woman wearing hat, woman holding phone, , hat on woman, ear of woman, , ear of woman, ear of woman, ear of woman, , shirt on woman, woman holding glass, man wearing shirt,  , ear of woman, , woman wearing hat, ear of woman, shirt on woman,   , shirt on woman, ear of woman,  , woman in car,  , shirt on woman, arm of woman, man wearing shirt, man wearing glass,  , woman holding phone, hand of woman, ear of woman, , woman wearing hat, hat on woman, , hat on head, ear of woman, shirt on woman, , shirt on woman, woman wearing hat, , man wearing shirt, man wearing hat, shirt on woman, , woman wearing hat, shirt on woman, helmet on woman, , woman in car, man in car, , shirt on woman, , woman wearing hat, man wearing shirt, shirt on woman, , helmet on woman,   , woman wearing hat, man wearing hat, ear of woman, , woman wearing hat, , hat on head, hat on woman, woman wearing shirt,    , shirt on woman, woman wearing hat, helmet on woman, , woman in car, helmet on head, , woman wearing helmet, , woman wearing hat, man in car, shirt on woman, , shirt on woman, hat on head, , hat on woman, , woman wearing hat, helmet on head,  , woman wearing hat, woman on phone, , woman wearing hat, hat on head, hat on woman,  , hat on woman, woman wearing hat,  , man wearing shirt, man wearing hat, shirt on woman, , man in car, , woman wearing shirt, shirt on woman, hat on head, woman wearing hat, helmet on woman, helmet on head, ear of woman, , woman wearing hat, hat on woman, woman in car, boy wearing shirt, , man wearing shirt, boy in car, helmet on head, , shirt on woman, , man wearing shirt, man in car, , woman in car, , man wearing helmet, helmet on head, ear of woman, shirt on woman, , woman wearing hat,  , woman in car,  , hat on head, , shirt on woman, woman in car, ear of woman, shirt on woman, , woman in car, ear of woman, helmet on woman, , shirt on woman, man wearing shirt, man wearing hat, phone in hand, ear of woman, , shirt on woman, , hat on head, , shirt on woman, woman wearing hat, man wearing shirt, hand of woman, ear of woman, , ear of woman, shirt on woman, , man wearing shirt, man wearing hat, hand of woman, helmet on woman, ear of woman,  , woman in car, ear of woman, '

In [5]:
df.head()

,q_id,question,answer_type,Answers,video_id,start,end,subtitle,OIC_context,OIC_question,ans_idx,OIC_answer_llama,Match_llama,OIC_context_without_CUID,OIC_context_without_CUID_temp
0,1011,How many people are in the car?,V,"['11', '4', '2', '7']",TGUYv10XdTI,19.328,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,How many people are in the car?Guess the most ...,2,2,Correct,The scene opens with woman wearing shirt\nwoma...,"woman wearing shirt, woman in car, woman wear..."
1,1012,What color is the man's hat?,V,"['silver', 'golden', 'blue', 'red']",TGUYv10XdTI,19.328,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,What color is the man's hat?Guess the most lik...,2,1,Wrong,The scene opens with woman wearing shirt\nwoma...,"woman wearing shirt, woman in car, woman wear..."
2,1013,Where are they?,B,"['restroom', 'train', 'bedroom', 'car']",TGUYv10XdTI,19.328,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,Where are they?Guess the most likely answer am...,3,2,Wrong,The scene opens with woman wearing shirt\nwoma...,"woman wearing shirt, woman in car, woman wear..."
3,1014,Where are they going?,L,"['class', 'restroom', 'party', 'mall']",TGUYv10XdTI,19.328,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,Where are they going?Guess the most likely ans...,3,2,Wrong,The scene opens with woman wearing shirt\nwoma...,"woman wearing shirt, woman in car, woman wear..."
4,1015,Where does she want to go to first?,L,"['Aldo', 'home', 'Zara', 'Forever XXI']",TGUYv10XdTI,19.328,76.650667,[boy] hello [girl] hey\n[boy] where are we goi...,The scene opens with woman_766a wearing shirt_...,Where does she want to go to first?Guess the m...,3,2,Wrong,The scene opens with woman wearing shirt\nwoma...,"woman wearing shirt, woman in car, woman wear..."

In [6]:
main=df
import ast
q_ids = main['q_id'].unique()
i=0
for qid in q_ids:
  #if 'Seq' in q:
    que = main.query("q_id=={}".format(qid))
    question = que['question'].values[0]
    answer_id = que["ans_idx"].values[0]
    subtitle = que['subtitle'].values[0]
    context = que['OIC_context_without_CUID_temp'].values[0]
    #print(context)
    
    prompt = context
    
    
    options = ast.literal_eval(que['Answers'].values[0])
    choice_string = ''

    choice_string = "0: {}, 1: {}, 2: {}, 3: {}".format(options[0], options[1], options[2], options[3])
    
    formatted_question = question+ 'Guess the most likely answer among these options: '+choice_string+' Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.'
    print('-'*100)
    print(i)
    #print(formatted_question)
    #response = run_gpt(prompt+'\n subtitle: '+subtitle, formatted_question)
    #response = run_gpt(prompt, formatted_question)
    response = run_llama(prompt, formatted_question)
    main.loc[main['q_id'] == qid, 'OIC_answer_llama'] = str(response)
    main.loc[main['q_id'] == qid, 'OIC_question'] = formatted_question
    main.loc[main['q_id'] == qid, 'OIC_context'] = prompt
    OIC_answer = response
    print('OIC question: {}'.format(formatted_question))
    print(choice_string)
    print('OIC answer: {}'.format(OIC_answer))
    if len(OIC_answer)>1:
      main.loc[main['q_id'] == qid, 'Match_llama_wo_CUID_temp'] = OIC_answer
    else:
      if int(OIC_answer) == int(answer_id):
          main.loc[main['q_id'] == qid, 'Match_llama_wo_CUID_temp'] = 'Correct'
          print('correct')
      else:
          print('wrong')
          main.loc[main['q_id'] == qid, 'Match_llama_wo_CUID_temp'] = 'Wrong'
    
    main.to_csv('LifeQA/for_eval/new/OIC_llama_modified_wo_CUID_temp.csv')
    i=i+1

----------------------------------------------------------------------------------------------------
0
OIC question: How many people are in the car?Guess the most likely answer among these options: 0: 11, 1: 4, 2: 2, 3: 7 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 11, 1: 4, 2: 2, 3: 7
OIC answer: 2
correct
----------------------------------------------------------------------------------------------------
1
OIC question: What color is the man's hat?Guess the most likely answer among these options: 0: silver, 1: golden, 2: blue, 3: red Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: silver, 1: golden, 2: blue, 3: red
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
2
OIC question: Where are they?Guess the most likely answer among these options: 0: restroom, 1: train, 2: bedroom, 3: car Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: restroom, 1: train, 2: bedroom, 3: car
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
3
OIC question: Where are they going?Guess the most likely answer among these options: 0: class, 1: restroom, 2: party, 3: mall Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: class, 1: restroom, 2: party, 3: mall
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
4
OIC question: Where does she want to go to first?Guess the most likely answer among these options: 0: Aldo, 1: home, 2: Zara, 3: Forever XXI Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: Aldo, 1: home, 2: Zara, 3: Forever XXI
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
5
OIC question: Where are they?Guess the most likely answer among these options: 0: restroom, 1: car, 2: restaurant , 3: park Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: restroom, 1: car, 2: restaurant , 3: park
OIC answer: 1
correct
----------------------------------------------------------------------------------------------------
6
OIC question: How many people are in the video?Guess the most likely answer among these options: 0: 6, 1: 8, 2: 2, 3: 7 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 6, 1: 8, 2: 2, 3: 7
OIC answer: 2
correct
----------------------------------------------------------------------------------------------------
7
OIC question: Why the girl want to go to mall?Guess the most likely answer among these options: 0: go to cinema, 1: buy clothes, 2: buy food, 3: see her friends Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: go to cinema, 1: buy clothes, 2: buy food, 3: see her friends
OIC answer: 1
correct
----------------------------------------------------------------------------------------------------
8
OIC question: What's the color of the man's hat?Guess the most likely answer among these options: 0: black, 1: brown, 2: blue, 3: white Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: black, 1: brown, 2: blue, 3: white
OIC answer: 2
correct
----------------------------------------------------------------------------------------------------
9
OIC question: What is the little girl's name?Guess the most likely answer among these options: 0: Paisly, 1: Brice, 2: Paula, 3: Brooklyn Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: Paisly, 1: Brice, 2: Paula, 3: Brooklyn
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
10
OIC question: What is the little girl's favorite color?Guess the most likely answer among these options: 0: brown, 1: red, 2: white, 3: pink Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: brown, 1: red, 2: white, 3: pink
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
11
OIC question: How old is the little girl?Guess the most likely answer among these options: 0: 1, 1: 2, 2: 4, 3: 3 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 1, 1: 2, 2: 4, 3: 3
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
12
OIC question: How many girls love pink?Guess the most likely answer among these options: 0: 4, 1: 1, 2: 2, 3: 3 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 4, 1: 1, 2: 2, 3: 3
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
13
OIC question: What does the little girl have pink?Guess the most likely answer among these options: 0: her fingernails, 1: her lips, 2: her skirt, 3: her t-shirt Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: her fingernails, 1: her lips, 2: her skirt, 3: her t-shirt
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
14
OIC question: What is on the woman's shirt?Guess the most likely answer among these options: 0: a dog, 1: a frog, 2: a cat, 3: an apple Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: a dog, 1: a frog, 2: a cat, 3: an apple
OIC answer: 2
correct
----------------------------------------------------------------------------------------------------
15
OIC question: How many people are there?Guess the most likely answer among these options: 0: 3, 1: 4, 2: 2, 3: 1 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 3, 1: 4, 2: 2, 3: 1
OIC answer: 2
correct
----------------------------------------------------------------------------------------------------
16
OIC question: What is the pattern according to the woman before the child changed it?Guess the most likely answer among these options: 0: spider, bee, spider, bee, bee, 1: bee, bee, spider, spider, 2: bee, bee, spider, bee, bee, 3: bee, spider, spider, bee, bee Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: spider, bee, spider, bee, bee, 1: bee, bee, spider, spider, 2: bee, bee, spider, bee, bee, 3: bee, spider, spider, bee, bee
OIC answer: 2
correct
----------------------------------------------------------------------------------------------------
17
OIC question: How many spiders does the boy add?Guess the most likely answer among these options: 0: 4, 1: 1, 2: 0, 3: 5 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 4, 1: 1, 2: 0, 3: 5
OIC answer: 1
correct
----------------------------------------------------------------------------------------------------
18
OIC question: What does the pattern contain?Guess the most likely answer among these options: 0:  spiders and cats, 1: bees and cars, 2: bees and flies, 3: bees and spiders Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0:  spiders and cats, 1: bees and cars, 2: bees and flies, 3: bees and spiders
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
19
OIC question: What does the pattern should have at the end to be correct?Guess the most likely answer among these options: 0: thtree spiders, 1: 2 bees, 2: 1 spider, 3: 2 spiders Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: thtree spiders, 1: 2 bees, 2: 1 spider, 3: 2 spiders
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
20
OIC question: What insect is on the first card in the row?Guess the most likely answer among these options: 0: a bee, 1: a fly, 2: a butterfly, 3: a beetle Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: a bee, 1: a fly, 2: a butterfly, 3: a beetle
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
21
OIC question: How many people are there?Guess the most likely answer among these options: 0: 2, 1: 3, 2: 4, 3: 1 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 2, 1: 3, 2: 4, 3: 1
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
22
OIC question: How many boys are there?Guess the most likely answer among these options: 0: 4, 1: 1, 2: 3, 3: 2 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 4, 1: 1, 2: 3, 3: 2
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
23
OIC question: How many women are there?Guess the most likely answer among these options: 0: 4, 1: 2, 2: 3, 3: 1 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 4, 1: 2, 2: 3, 3: 1
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
24
OIC question: What are they doing?Guess the most likely answer among these options: 0: playing video games, 1: singing, 2: playing cards, 3: dancing Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: playing video games, 1: singing, 2: playing cards, 3: dancing
OIC answer: 2
correct
----------------------------------------------------------------------------------------------------
25
OIC question: How many TVs are in this house?Guess the most likely answer among these options: 0: 4, 1: 3, 2: 1, 3: 2 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 4, 1: 3, 2: 1, 3: 2
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
26
OIC question: How many times you get to blow bubbles?Guess the most likely answer among these options: 0: 4, 1: 3, 2: 1, 3: 2 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 4, 1: 3, 2: 1, 3: 2
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
27
OIC question: How many people are in the video?Guess the most likely answer among these options: 0: 1, 1: 5, 2: 2, 3: 3 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 1, 1: 5, 2: 2, 3: 3
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
28
OIC question: Who is the girl in relation to the woman?Guess the most likely answer among these options: 0: sister, 1: daughter, 2: cousin, 3: aunt Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: sister, 1: daughter, 2: cousin, 3: aunt
OIC answer: 1
correct
----------------------------------------------------------------------------------------------------
29
OIC question: What is the first rule to have a turn?Guess the most likely answer among these options: 0: wait, 1: play, 2: talk, 3: listen Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: wait, 1: play, 2: talk, 3: listen
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
30
OIC question: What color is the woman's top?Guess the most likely answer among these options: 0: orange, 1: white, 2: red, 3: magenta Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: orange, 1: white, 2: red, 3: magenta
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
31
OIC question: What does the woman do with the liquid?Guess the most likely answer among these options: 0: drinks it, 1: throws it away, 2: pours it, 3: spills it Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: drinks it, 1: throws it away, 2: pours it, 3: spills it
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
32
OIC question: Where are they?Guess the most likely answer among these options: 0: court, 1: classroom, 2: backyard, 3: floor Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: court, 1: classroom, 2: backyard, 3: floor
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
33
OIC question: How many empty cups are?Guess the most likely answer among these options: 0: 5, 1: 2, 2: 3, 3: 1 Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: 5, 1: 2, 2: 3, 3: 1
OIC answer: 2
wrong
----------------------------------------------------------------------------------------------------
34
OIC question: What color is the liquid?Guess the most likely answer among these options: 0: blue, 1: green, 2: black, 3: red Respond with a only a single integer between 0 and 3. Do not produce any other or verbose answers. If enough information is not given, still make a guess to result in one out of the given options. Do not explain yourself, answer with only an integer value.
0: blue, 1: green, 2: black, 3: red
OIC answer: 1
wrong
----------------------------------------------------------------------------------------------------
35